[env:m5stack-core]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@^0.4.6
    bblanchon/ArduinoJson@^7.0.0
    ricmoo/QRCode@^0.0.1
upload_speed = 921600
; huge_app: app0=3MB (OTAなし), NVSは使用可能
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Os
